CREATE SCHEMA `SIS2402`;

USE `SIS2402`;

CREATE TABLE `SIS2402`.`CLIENTES`(
	`ID_CLIENTE` INT NOT NULL AUTO_INCREMENT,
	`NOME` MEDIUMTEXT NOT NULL,
    `EMAIL` VARCHAR(50) NOT NULL,
    `NASCIMENTO` DATE NOT NULL,
    `GENERO` VARCHAR(9) NOT NULL,
    `CEP` VARCHAR(9) NOT NULL,
    `RUA` LONGTEXT NOT NULL,
    `NUMERO` INT NOT NULL,
    `BAIRRO` TEXT NOT NULL,
    `CIDADE` MEDIUMTEXT NOT NULL,
    `UF` VARCHAR(2) NOT NULL,
    `PAIS` TEXT NOT NULL,    
	PRIMARY KEY(`ID_CLIENTE`)
);

-- INSERINDO DADOS NA TABELA
INSERT INTO `SIS2402`.`CLIENTES` (`NOME`, `EMAIL`, `NASCIMENTO`, `GENERO`, `CEP`, `RUA`, `NUMERO`, `BAIRRO`, `CIDADE`, `UF`, `PAIS`)
VALUES('Layne', 'layfirmino@email.com', '2002-02-02', 'feminino', '89560-700', 'Rua São João', 1000, 'Aparecida', 'Videira', 'SC', 'Brasil');

-- EXIBINDO/CONSULTANDO DADOS
SELECT * FROM `SIS2402`.`CLIENTES`;