INSERT INTO `NOTA_FISCAL`(
	NM_CLIENTE, 
    END_CLIENTE, 
    NM_VENDEDOR, 
    VL_TOTAL)
VALUES ('Smeagol', 'Pântano', 'Sauron', 99.00);

SELECT * FROM NOTA_FISCAL
WHERE NM_CLIENTE = 'Smeagol';

INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
	VALUES (5, 1, 1, 4.50, 4.50);
    
INSERT INTO `ITEM_NOTA_FISCAL` (NRO_NOTA, COD_PRODUTO, QTD_PRODUTO, VL_PRECO, VL_TOTAL)
	VALUES (5, 2, 1, 5.50, 5.50);
    
SELECT * FROM ITEM_NOTA_FISCAL WHERE NRO_NOTA = 5;
    
INSERT INTO `NOTA_FISCAL`(
	NM_CLIENTE, 
    END_CLIENTE, 
    NM_VENDEDOR, 
    VL_TOTAL)
VALUES ('Gimly', 'Montanha', 'Thorin', 9999.00);

INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO)
VALUES('Queijo', 'Kg', '30');

INSERT INTO `PRODUTO` (DESC_PRODUTO, UN_MED, VL_PRODUTO)
VALUES('Copa', 'Kg', '70');