CREATE DATABASE CADASTRO_FUNCIONARIO;
USE CADASTRO_FUNCIONARIO;

CREATE TABLE DEPARTAMENTO(
    NOME VARCHAR(256) UNIQUE NOT NULL PRIMARY KEY,
    DT_INICIO DATE NOT NULL,
    DT_FIM DATE NOT NULL 
);

CREATE TABLE CARGO(
	NOME VARCHAR(256) UNIQUE NOT NULL PRIMARY KEY,
    DT_INICIO DATE NOT NULL,
    DT_FIM DATE NOT NULL
);

CREATE TABLE FUNCIONARIO(
	MATRICULA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(256) NOT NULL,
    NASCIMENTO DATE NOT NULL,
    NACIONALIDADE VARCHAR(50) NOT NULL,
    GENERO VARCHAR(10) NOT NULL,
    EST_CIVIL VARCHAR(10) NOT NULL,
    RG VARCHAR(12) UNIQUE NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    ENDERECO VARCHAR(256) NOT NULL,
    TELEFONE VARCHAR(14) NOT NULL,
    DT_ADMISSAO DATE NOT NULL,
    FK_NOME_DPTO VARCHAR(256) NOT NULL,
    FK_NOME_CARGO VARCHAR(256) NOT NULL,
    
    CONSTRAINT FK_FUNCIONARIO_NOME_DPTO FOREIGN KEY (FK_NOME_DPTO) REFERENCES DEPARTAMENTO(NOME),
    CONSTRAINT FK_FUNCIONARIO_NOME_CARGO FOREIGN KEY (FK_NOME_CARGO) REFERENCES CARGO(NOME)
);

CREATE TABLE DEPENDENTE(
	FK_MATRICULA INT NOT NULL,
    NOME VARCHAR(256) NOT NULL,
    NASCIMENTO DATE NOT NULL,
    
    PRIMARY KEY(FK_MATRICULA, NOME),
    CONSTRAINT FK_MATRICULA_FUNCIONARIO_DEPENDENTE
		FOREIGN KEY(FK_MATRICULA) REFERENCES FUNCIONARIO(MATRICULA)
);









INSERT INTO DEPARTAMENTO (NOME, DT_INICIO, DT_FIM)
	VALUES ('Tecnologia', '2023-05-10', '2023-05-11');

INSERT INTO CARGO (NOME, DT_INICIO, DT_FIM)
	VALUES ('Assistente', '2023-05-10', '2023-05-11');
    
INSERT INTO DEPARTAMENTO (NOME, DT_INICIO, DT_FIM)
	VALUES ('Açougue', '2023-05-10', '2023-05-17');

INSERT INTO CARGO (NOME, DT_INICIO, DT_FIM)
	VALUES ('Açougueiro', '2023-05-10', '2023-05-17');

INSERT INTO FUNCIONARIO (NOME, NASCIMENTO, NACIONALIDADE, GENERO, EST_CIVIL, RG, CPF, ENDERECO, TELEFONE, DT_ADMISSAO, FK_NOME_DPTO, FK_NOME_CARGO)
	VALUES ('Layne Firmino', '2005-03-17', 'Brasileiro', 'Feminino', 'Solteiro', '00.539.000-7', '100.700.200-50', 'Rua 01', '49998988989', '2023-05-10', 'Tecnologia', 'Assistente');
    
INSERT INTO FUNCIONARIO (NOME, NASCIMENTO, NACIONALIDADE, GENERO, EST_CIVIL, RG, CPF, ENDERECO, TELEFONE, DT_ADMISSAO, FK_NOME_DPTO, FK_NOME_CARGO)
	VALUES ('Alex Firmino', '1996-03-17', 'Brasileiro', 'Masculino', 'Solteiro', '00.500.000-7', '100.700.200-60', 'Rua 02', '49998988985', '2023-03-15', 'Açougue', 'Açougueiro');
    
INSERT INTO DEPENDENTE (FK_MATRICULA, NOME, NASCIMENTO)
	VALUES (1, 'Alice', '2023-02-02');

INSERT INTO DEPENDENTE (FK_MATRICULA, NOME, NASCIMENTO)
	VALUES (1, 'Marcos', '2023-02-02');
    
INSERT INTO DEPENDENTE (FK_MATRICULA, NOME, NASCIMENTO)
	VALUES (2, 'Ana', '2023-05-02');
    
SELECT * FROM FUNCIONARIO;