USE `BD2401`;

-- Excluindo o BD
-- DROP DATABASE `BD2401`;
-- Criando o Schema do BD
CREATE SCHEMA `BD2401`;
-- Criando a tabela
CREATE TABLE `BD2401`.`NEW_TABLE`(
	`ID_MEMBER` INT NOT NULL AUTO_INCREMENT,
    `FIRST_NAME` VARCHAR(20) NOT NULL,
    `ACTIVE` BIT(1) NULL DEFAULT 1,
    `WHEN_ADDED` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    `LAST_MODIFIED` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`ID_MEMBER`)
);

-- Inserindo Dados na tabela
INSERT INTO `BD2401`.`NEW_TABLE` (`FIRST_NAME`)
VALUES('Layne Firmino');

INSERT INTO `BD2401`.`NEW_TABLE` (`FIRST_NAME`, `ACTIVE`)
VALUES('Alex Rafael Oneda', 0);

INSERT INTO `BD2401`.`NEW_TABLE` (`FIRST_NAME`, `ACTIVE`)
VALUES('Rafaela Correa', 0);

-- Exibindo/Consultando Dados
SELECT * FROM `BD2401`.`NEW_TABLE`;